apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: 192.168.44.44:8082/docker_registry/backend:latest  
        name: backend
        resources: {}
        ports:
        - containerPort: 5001
      imagePullSecrets:
      - name: regcred
status: {}
